-- Seed data migrated from the hardcoded arrays in script.js
-- Run this AFTER api/db.sql so the menu_items table already exists.
USE flaverheaven;

INSERT INTO menu_items (name, description, price, category, type, image, available) VALUES
('Margherita Pizza', 'Fresh mozzarella, tangy tomato sauce, and basil on a crispy baked crust.', 349, 'pizza', 'veg', 'Images/FoodItems/Pizza/Pizza1.jpg', 1),
('Veg Pizza', 'Loaded with fresh vegetables, mozzarella cheese, and Italian herbs on a crispy crust.', 399, 'pizza', 'veg', 'Images/FoodItems/Pizza/Pizza2.jpg', 1),
('Farmhouse Pizza', 'Fresh mushrooms, onions, tomatoes, capsicum, and sweet corn topped with melted cheese.', 429, 'pizza', 'veg', 'Images/FoodItems/Pizza/Pizza3.jpg', 1),
('Paneer Tikka Pizza', 'Spicy paneer tikka, onions, and capsicum layered with mozzarella cheese.', 459, 'pizza', 'veg', 'Images/FoodItems/Pizza/Pizza4.jpg', 1),
('Veg Burger', 'Crispy vegetable patty layered with fresh greens and sauce.', 199, 'burgers', 'veg', 'Images/FoodItems/Veg/Burger/Burger1.jpg', 1),
('Paneer Burger', 'Grilled paneer with caramelized onions and herb mayo.', 249, 'burgers', 'veg', 'Images/FoodItems/Veg/Burger/Burger2.jpg', 1),
('Cheese Burger', 'Double cheese indulgence with a juicy molten center.', 279, 'burgers', 'veg', 'Images/FoodItems/Veg/Burger/Burger3.jpg', 1),
('Peri Peri Burger', 'Spicy peri peri sauce with crunchy lettuce and pickles.', 299, 'burgers', 'veg', 'Images/FoodItems/Veg/Burger/Burger4.jpg', 1),
('White Sauce Pasta', 'Creamy pasta with a velvety cheese sauce and herbs.', 249, 'pasta', 'veg', 'Images/FoodItems/Veg/Pasta/Pasta1.jpg', 1),
('Red Sauce Pasta', 'Tangy tomato sauce with a comforting homemade finish.', 229, 'pasta', 'veg', 'Images/FoodItems/Veg/Pasta/Pasta2.jpg', 1),
('Pink Sauce Pasta', 'Silky blend of tomato and cream for a rich bite.', 269, 'pasta', 'veg', 'Images/FoodItems/Veg/Pasta/Pasta3.jpg', 1),
('Alfredo Pasta', 'Butter-rich Alfredo pasta with sautéed mushrooms.', 289, 'pasta', 'veg', 'Images/FoodItems/Veg/Pasta/Pasta4.jpg', 1),
('Crispy French Fries', 'Golden fries with a crunchy exterior and soft center.', 129, 'snacks', 'veg', 'Images/FoodItems/Veg/Snacks/Snacks1.jpg', 1),
('Peri Peri Fries', 'Spiced fries with a zesty kick and peppery aroma.', 149, 'snacks', 'veg', 'Images/FoodItems/Veg/Snacks/Snacks2.jpg', 1),
('Cheese Garlic Bread', 'Toasted garlic bread with bubbling cheese on top.', 189, 'snacks', 'veg', 'Images/FoodItems/Veg/Snacks/Snacks3.jpg', 1),
('Veg Momos', 'Steamed dumplings served with house spice chutney.', 199, 'snacks', 'veg', 'Images/FoodItems/Veg/Snacks/Snacks4.jpg', 1),
('Green Salad', 'Fresh lettuce, cucumber, tomatoes, and carrots tossed with herbs.', 169, 'salads', 'veg', 'Images/FoodItems/Veg/Salad/Salad1.jpg', 1),
('Caesar Salad', 'Crisp romaine lettuce mixed with parmesan, croutons, and creamy dressing.', 209, 'salads', 'veg', 'Images/FoodItems/Veg/Salad/Salad2.jpg', 1),
('Greek Salad', 'Juicy tomatoes, cucumbers, olives, onions, and feta cheese tossed together.', 229, 'salads', 'veg', 'Images/FoodItems/Veg/Salad/Salad3.jpg', 1),
('Paneer Tikka Salad', 'Grilled paneer cubes served with fresh vegetables and mint dressing.', 259, 'salads', 'veg', 'Images/FoodItems/Veg/Salad/Salad4.jpg', 1),
('Espresso', 'Bold aromatic shot with a rich crema finish.', 129, 'coffee', 'veg', 'Images/FoodItems/Drink/Coffee/Coffee1.jpg', 1),
('Cappuccino', 'Creamy coffee with double-shot espresso and foam.', 179, 'coffee', 'veg', 'Images/FoodItems/Drink/Coffee/Coffee2.jpg', 1),
('Latte', 'Silky milk latte with a mellow espresso flavor.', 199, 'coffee', 'veg', 'Images/FoodItems/Drink/Coffee/Coffee3.jpg', 1),
('Mocha', 'Chocolate-rich coffee with a sweet finish.', 219, 'coffee', 'veg', 'Images/FoodItems/Drink/Coffee/Coffee4.jpg', 1),
('Masala Tea', 'Warm spiced chai with refreshing masala notes.', 89, 'tea', 'veg', 'Images/FoodItems/Drink/Tea/Tea1.jpg', 1),
('Green Tea', 'Gentle green tea with a clean, calming finish.', 99, 'tea', 'veg', 'Images/FoodItems/Drink/Tea/Tea2.jpg', 1),
('Lemon Tea', 'Bright citrus tea served hot or iced.', 109, 'tea', 'veg', 'Images/FoodItems/Drink/Tea/Tea3.jpg', 1),
('Ginger Tea', 'Fresh ginger tea with a warm, soothing flavor.', 119, 'tea', 'veg', 'Images/FoodItems/Drink/Tea/Tea4.jpg', 1),
('Fresh Lime Soda', 'Sparkling citrus cooler with a minty twist.', 119, 'beverages', 'veg', 'Images/FoodItems/Drink/Beverages/Beverages1.jpg', 1),
('Mango Shake', 'Creamy mango shake with ripe tropical flavor.', 169, 'beverages', 'veg', 'Images/FoodItems/Drink/Beverages/Beverages2.jpg', 1),
('Chocolate Shake', 'Rich chocolate milkshake topped with whipped cream.', 179, 'beverages', 'veg', 'Images/FoodItems/Drink/Beverages/Beverages3.jpg', 1),
('Oreo Shake', 'Creamy vanilla shake blended with Oreo crunch.', 189, 'beverages', 'veg', 'Images/FoodItems/Drink/Beverages/Beverages4.jpg', 1),
('Chocolate Brownie', 'Fudgy brownie with a gooey chocolate core.', 189, 'desserts', 'veg', 'Images/FoodItems/Desserts/Desserts1.jpg', 1),
('Chocolate Lava Cake', 'Warm cake with a molten chocolate center.', 229, 'desserts', 'veg', 'Images/FoodItems/Desserts/Desserts2.jpg', 1),
('Vanilla Ice Cream', 'Classic scoop served with a delicate vanilla note.', 149, 'desserts', 'veg', 'Images/FoodItems/Desserts/Desserts3.jpg', 1),
('Chocolate Ice Cream', 'Velvety ice cream with a rich cocoa finish.', 159, 'desserts', 'veg', 'Images/FoodItems/Desserts/Desserts4.jpg', 1),
('Paneer Butter Masala', 'Silky paneer curry with buttery tomato gravy.', 279, 'maincourse', 'veg', 'Images/FoodItems/Veg/MainCource/MainCource1.jpg', 1),
('Veg Kolhapuri', 'A bold and spicy coconut-based vegetable curry.', 259, 'maincourse', 'veg', 'Images/FoodItems/Veg/MainCource/MainCource2.jpg', 1),
('Dal Tadka', 'Slow-cooked lentils tempered with aromatic spices.', 229, 'maincourse', 'veg', 'Images/FoodItems/Veg/MainCource/MainCource3.jpg', 1),
('Veg Biryani', 'Layered basmati rice with fragrant vegetables and herbs.', 299, 'maincourse', 'veg', 'Images/FoodItems/Veg/MainCource/MainCource4.jpg', 1),
('Heaven Special Pizza', 'Chef’s signature pizza with premium toppings and herbs.', 499, 'chefspecial', 'veg', 'Images/FoodItems/Chefspecial/Chefspecial1.jpg', 1),
('Signature Alfredo Pasta', 'Creamy pasta crafted with a decadent chef’s touch.', 379, 'chefspecial', 'veg', 'Images/FoodItems/Veg/Chefspecial/Chefspecial2.jpg', 1),
('Heaven Supreme Burger', 'A stacked burger with premium fillings and secret sauce.', 329, 'chefspecial', 'veg', 'Images/FoodItems/Veg/Chefspecial/Chefspecial3.jpg', 1),
('Tropical Mocktail', 'Refreshing mocktail with citrus, mint, and tropical fruit.', 189, 'chefspecial', 'veg', 'Images/FoodItems/Veg/Chefspecial/Chefspecial4.jpg', 1),
('Chicken Supreme Pizza', 'Grilled chicken, mozzarella cheese, and Italian herbs on a crispy crust.', 449, 'pizza', 'nonveg', 'Images/FoodItems/NonVeg/Pizza/Pizza1.jpg', 1),
('Pepperoni Pizza', 'Classic pepperoni slices layered with mozzarella and rich tomato sauce.', 499, 'pizza', 'nonveg', 'Images/FoodItems/NonVeg/Pizza/Pizza2.jpg', 1),
('BBQ Chicken Pizza', 'Smoky BBQ chicken topped with onions, cheese, and flavorful herbs.', 529, 'pizza', 'nonveg', 'Images/FoodItems/NonVeg/Pizza/Pizza3.jpg', 1),
('Chicken Tikka Pizza', 'Spicy chicken tikka with onions, capsicum, and mozzarella cheese.', 549, 'pizza', 'nonveg', 'Images/FoodItems/NonVeg/Pizza/Pizza4.jpg', 1),
('Chicken Burger', 'Juicy grilled chicken served with lettuce and creamy mayonnaise.', 249, 'burgers', 'nonveg', 'Images/FoodItems/NonVeg/Burger/Burger1.jpg', 1),
('Crispy Chicken Burger', 'Crunchy fried chicken with fresh vegetables and signature sauce.', 279, 'burgers', 'nonveg', 'Images/FoodItems/NonVeg/Burger/Burger2.jpg', 1),
('Grilled Chicken Burger', 'Tender grilled chicken with cheese and smoky barbecue sauce.', 299, 'burgers', 'nonveg', 'Images/FoodItems/NonVeg/Burger/Burger3.jpg', 1),
('Double Chicken Burger', 'Double chicken patties layered with cheese and fresh vegetables.', 349, 'burgers', 'nonveg', 'Images/FoodItems/NonVeg/Burger/Burger4.jpg', 1),
('Chicken Alfredo Pasta', 'Creamy Alfredo pasta served with grilled chicken and herbs.', 329, 'pasta', 'nonveg', 'Images/FoodItems/NonVeg/Pasta/Pasta1.jpg', 1),
('Chicken Arrabbiata Pasta', 'Spicy tomato pasta mixed with juicy chicken pieces and herbs.', 319, 'pasta', 'nonveg', 'Images/FoodItems/NonVeg/Pasta/Pasta2.jpg', 1),
('Creamy Chicken Pasta', 'Tender chicken blended with creamy white sauce and parmesan cheese.', 339, 'pasta', 'nonveg', 'Images/FoodItems/NonVeg/Pasta/Pasta3.jpg', 1),
('Chicken Pesto Pasta', 'Fresh basil pesto pasta tossed with grilled chicken and parmesan.', 349, 'pasta', 'nonveg', 'Images/FoodItems/NonVeg/Pasta/Pasta4.jpg', 1),
('Chicken Momos', 'Steamed chicken dumplings served with spicy house-made chutney.', 229, 'snacks', 'nonveg', 'Images/FoodItems/NonVeg/Snacks/Snacks1.jpg', 1),
('Chicken Nuggets', 'Golden crispy chicken nuggets served with creamy garlic dip.', 249, 'snacks', 'nonveg', 'Images/FoodItems/NonVeg/Snacks/Snacks2.jpg', 1),
('Chicken Wings', 'Crispy chicken wings coated with spicy barbecue seasoning.', 289, 'snacks', 'nonveg', 'Images/FoodItems/NonVeg/Snacks/Snacks3.jpg', 1),
('Chicken Popcorn', 'Bite-sized crispy chicken pieces served with tangy dipping sauce.', 259, 'snacks', 'nonveg', 'Images/FoodItems/NonVeg/Snacks/Snacks4.jpg', 1),
('Grilled Chicken Salad', 'Fresh vegetables topped with juicy grilled chicken and herbs.', 299, 'salads', 'nonveg', 'Images/FoodItems/NonVeg/Salad/Salad1.jpg', 1),
('Chicken Caesar Salad', 'Classic Caesar salad served with grilled chicken and parmesan.', 319, 'salads', 'nonveg', 'Images/FoodItems/NonVeg/Salad/Salad2.jpg', 1),
('Mediterranean Chicken Salad', 'Fresh vegetables mixed with grilled chicken and olive dressing.', 329, 'salads', 'nonveg', 'Images/FoodItems/NonVeg/Salad/Salad3.jpg', 1),
('Spicy Chicken Salad', 'Seasoned chicken tossed with crunchy vegetables and fresh herbs.', 309, 'salads', 'nonveg', 'Images/FoodItems/NonVeg/Salad/Salad4.jpg', 1),
('Butter Chicken', 'Tender chicken cooked in rich buttery tomato gravy and cream.', 399, 'maincourse', 'nonveg', 'Images/FoodItems/NonVeg/MainCourse/MainCourse1.jpg', 1),
('Chicken Biryani', 'Fragrant basmati rice layered with spiced chicken and herbs.', 379, 'maincourse', 'nonveg', 'Images/FoodItems/NonVeg/MainCourse/MainCourse2.jpg', 1),
('Chicken Curry', 'Traditional chicken curry prepared with aromatic Indian spices.', 359, 'maincourse', 'nonveg', 'Images/FoodItems/NonVeg/MainCourse/MainCourse3.jpg', 1),
('Mutton Rogan Josh', 'Slow-cooked mutton in rich Kashmiri spices and flavorful gravy.', 499, 'maincourse', 'nonveg', 'Images/FoodItems/NonVeg/MainCourse/MainCourse4.jpg', 1),
('Signature Chicken Pizza', 'Chef-crafted pizza loaded with premium chicken and mozzarella.', 599, 'chefspecial', 'nonveg', 'Images/FoodItems/NonVeg/Chefspecial/Chefspecial1.jpg', 1),
('Creamy Chicken Alfredo', 'Chef special Alfredo pasta topped with grilled chicken pieces.', 429, 'chefspecial', 'nonveg', 'Images/FoodItems/NonVeg/Chefspecial/Chefspecial2.jpg', 1),
('Ultimate Chicken Burger', 'Double grilled chicken burger with cheese and special sauce.', 399, 'chefspecial', 'nonveg', 'Images/FoodItems/NonVeg/Chefspecial/Chefspecial3.jpg', 1),
('Chicken Sizzler', 'Hot sizzling chicken served with vegetables and flavorful sauce.', 549, 'chefspecial', 'nonveg', 'Images/FoodItems/NonVeg/Chefspecial/Chefspecial4.jpg', 1);
